spring:
  application:
    name: todolist
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

app:
  name: DefaultApp
  values:
    - default1
    - default2
  env-variable: ${EXAMPLE_TEST:default}

request:
  limit:
    max: 5

rabbit:
  queue:
    name: homework.queue
  exchange:
    name: homework.exchange
  routing:
    key: homework.key
